// FILE: src/agents/researchAgent.js
// Agent 1 — Research Agent (Mock)
// Returns a hyper-realistic ranked product shortlist with full research documents

export async function runResearchAgent(config, _context = {}) {
  const { market = {}, niche = {}, exclusions = {} } = config;

  // ── Hyper-realistic research output ─────────────────────────────
  return {
    agentId: "research",
    market:  market.country  || "United Kingdom",
    niche:   niche.niche     || "Outdoor & Travel",
    language: market.language || "English",
    researchSources: ["TikTok Trending", "Amazon Best Sellers", "Google Trends", "Meta Ads Library", "Reddit r/BuyItForLife", "Trustpilot Reviews"],
    researchSummary: "Analysed 340+ products across 12 niches. Applied 10-item research checklist to every candidate. Auto-filtered restricted categories. Final shortlist represents products with confirmed viral demand signals, proven emotional triggers, and viable margins at the target price point.",
    exclusionsApplied: exclusions.excluded || [],
    products: [
      {
        rank: 1,
        name: "Posture Corrector Pro",
        category: "Health & Wellness",
        emoji: "🦴",
        trendScore: 94,
        checklistScore: 9,
        sellingPrice: 49,
        estimatedCOGS: 8,
        grossMargin: 84,
        competitors: 12,
        adLongevity: "6+ months",
        sources: ["TikTok", "Amazon", "Reddit"],
        demandSignal: "Viral on TikTok — 180M+ views on #PostureFix. Amazon BSR #3 in Back Support. Meta Ads Library shows 14 active advertisers spending consistently for 6+ months — strong signal of profitable market.",
        avatar: {
          name: "Office Worker",
          ageRange: "28–45",
          corePain: "Chronic neck & back pain from 8+ hours at a desk daily",
          motivation: "Fear of irreversible spinal damage + desire to look confident",
          location: "Urban professional, hybrid WFH setup",
        },
        verbatimQuotes: [
          "\"My neck hurts so bad after 8 hours at my desk — I wake up stiff every single morning\"",
          "\"I've tried foam rollers, physio, everything — nothing actually fixes the root problem\"",
          "\"I look completely hunched in every photo and I hate it — my posture was perfect as a kid\"",
          "\"My GP told me I'm developing kyphosis and I'm only 34. That genuinely scared me.\"",
        ],
        failedSolutions: [
          "Foam rollers ($) — temporary relief, requires daily effort",
          "Physiotherapy (£80–£120/session) — expensive, not sustainable",
          "YouTube stretch routines — require discipline, most stop within 2 weeks",
          "Posture reminder apps — notification fatigue, ignored after day 3",
        ],
        emotionalLanguage: [
          "\"fix my posture for good\"",
          "\"finally something that actually works\"",
          "\"stop the pain without the physio bills\"",
          "\"feel confident standing straight again\"",
          "\"passive correction — no effort required\"",
        ],
        winningAdAngles: [
          "Pain angle: neck/back pain after WFH day",
          "Aspiration angle: stand tall, look confident in every room",
          "Social proof angle: 14,000 five-star reviews — what are they all doing differently?",
        ],
        researchChecklist: {
          laserTargetedAvatar: true,
          urgentProblem: true,
          emotionalImpact: true,
          umpIdentified: true,
          umsValidated: true,
          uspsDocumented: true,
          buyingPsychologyMapped: true,
          testimonialsFound: true,
          failedSolutionsCatalogued: true,
          marketSpecificKnowledge: false,
        },
      },
      {
        rank: 2,
        name: "Magnetic Phone Mount (Dashboard)",
        category: "Automotive",
        emoji: "🚗",
        trendScore: 87,
        checklistScore: 8,
        sellingPrice: 39,
        estimatedCOGS: 4,
        grossMargin: 90,
        competitors: 28,
        adLongevity: "12+ months",
        sources: ["Amazon", "Google Trends", "Meta Ads"],
        demandSignal: "Steady Google Trends growth — 3× YoY search volume increase. Amazon BSR consistently top 10 in Car Electronics. Category has 28 advertisers but top 3 own 60% of spend — gap for a differentiated entrant.",
        avatar: {
          name: "Daily Commuter",
          ageRange: "25–50",
          corePain: "Phone falls off mount while navigating, scratch risk, cable clutter",
          motivation: "Safety while driving + one-handed convenience",
          location: "Suburban driver, 30–60 min daily commute",
        },
        verbatimQuotes: [
          "\"My phone keeps falling off while I'm driving — nearly caused an accident\"",
          "\"Every mount I've bought scratches my phone case within a week\"",
          "\"Cable management in my car is an absolute nightmare — I hate it\"",
          "\"I just want something that actually holds my phone without me touching it\"",
        ],
        failedSolutions: [
          "Suction cup mounts — fall off in heat, leave residue on windscreen",
          "Vent clip holders — block airflow, can't see screen at angle",
          "Dashboard sticky pads — lose adhesion, look ugly",
        ],
        emotionalLanguage: [
          "\"just stays put\"",
          "\"one-hand mount\"",
          "\"clean dashboard setup\"",
          "\"never falls off\"",
          "\"actually safe to use while driving\"",
        ],
        winningAdAngles: [
          "Safety angle: distracted driving statistics + one-touch solution",
          "Convenience angle: the 3-second phone mount that works every time",
          "Clean aesthetic angle: before/after dashboard transformation",
        ],
        researchChecklist: {
          laserTargetedAvatar: true,
          urgentProblem: true,
          emotionalImpact: true,
          umpIdentified: true,
          umsValidated: false,
          uspsDocumented: true,
          buyingPsychologyMapped: true,
          testimonialsFound: true,
          failedSolutionsCatalogued: true,
          marketSpecificKnowledge: true,
        },
      },
      {
        rank: 3,
        name: "Foldable Laptop Stand",
        category: "Home Office",
        emoji: "💻",
        trendScore: 79,
        checklistScore: 7,
        sellingPrice: 35,
        estimatedCOGS: 6,
        grossMargin: 83,
        competitors: 41,
        adLongevity: "8+ months",
        sources: ["Amazon", "Reddit", "TikTok"],
        demandSignal: "Rising in Remote Work searches post-2023. TikTok #WFHSetup has 2.1B views. High competition (41 advertisers) suggests strong market but requires differentiation to enter profitably.",
        avatar: {
          name: "Remote Worker / Student",
          ageRange: "20–38",
          corePain: "Neck strain from looking down at laptop all day",
          motivation: "Ergonomic setup on a budget, portable for café working",
          location: "City dweller, coffee shop worker, student",
        },
        verbatimQuotes: [
          "\"My neck is absolutely destroyed from looking down at my MacBook for 8 hours\"",
          "\"Expensive standing desks aren't an option in my flat — I need something portable\"",
          "\"I work from cafés three days a week — need something I can throw in my bag\"",
        ],
        failedSolutions: [
          "Book stacks — unstable, looks ridiculous on video calls",
          "Bulky adjustable stands — too heavy to carry, inconvenient",
          "External monitors — expensive, not portable",
        ],
        emotionalLanguage: [
          "\"actually portable\"",
          "\"works anywhere\"",
          "\"saved my neck\"",
          "\"fits in my bag\"",
          "\"desk setup upgrade\"",
        ],
        winningAdAngles: [
          "Pain angle: neck pain from looking down at laptop",
          "Aesthetic angle: clean WFH desk setup transformation",
          "Portability angle: the stand that fits in your bag",
        ],
        researchChecklist: {
          laserTargetedAvatar: true,
          urgentProblem: true,
          emotionalImpact: false,
          umpIdentified: false,
          umsValidated: false,
          uspsDocumented: true,
          buyingPsychologyMapped: true,
          testimonialsFound: true,
          failedSolutionsCatalogued: true,
          marketSpecificKnowledge: true,
        },
      },
    ],
  };
}